name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - run: g++ -std=c++20 -Wall -Wextra -Werror -o test/main test/main.cpp
      - run: test/main

      - run: g++ -std=c++23 -Wall -Wextra -Werror -o test/main test/main.cpp
      - run: test/main

      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl /W3 /EHsc /std:c++20 test/main.cpp /link /out:test/main-msvc.exe
          call "test/main-msvc.exe"
        shell: cmd
